<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Bullet.Desktop</RootNamespace>
    <AssemblyName>Bullet</AssemblyName>
    <ApplicationIcon>Bullet.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Bullet.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3124.44" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bullet.Api\Bullet.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Bullet.Api\wwwroot\**" Link="wwwroot\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>

</Project>
